name: Web Config
type: module
description: 'Have the most needed configuration management modules with basic config.'
core_version_requirement: ^10
dependencies:
  - drupal:config
  - config_update:config_update
  - config_update:config_update_ui
  - config_filter:config_filter
  - config_normalizer:config_normalizer
  - config_partial_export:config_partial_export
  - config_import_single:config_import_single