name: Web Config
type: module
description: Web Configuration management. Most needed configuration management modules.'
core_version_requirement: ~10.2.0
dependencies:
  - drupal:config
  - config_update:config_update
  - config_update:config_update_ui
  - config_filter:config_filter
  - config_import_single:config_import_single
