name: Web Config - Default
description: A recipe to manage default installed modules, configs and permissions.
type: install
install:
  - config
  - config_update
  - config_update_ui
  - config_split
  - config_ignore
  - config_inspector
  - config_rewrite
  - config_import_single
  # Last, after its dependencies: the Web Config module itself.
  - webconfig
config:
  strict: false
  import:
    config_update: '*'
    config_split: '*'
    config_ignore: '*'
    config_inspector: '*'
    config_rewrite: '*'
    config_import_single: '*'
